baseURL = 'https://apologetics.club/'
languageCode = 'en-us'
title = 'Apologetics Club'
ignoreFiles = ['/.sass-cache']
enableRobotsTXT = true
enableEmoji = true
summaryLength = 20

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true